version: 2.1

orbs:
  scan: prisma_cloud/devops_security@1.0.0

jobs:
  docker-build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      
      - setup_remote_docker

      - run: 
          name: mvn package
          command: |
            cd web-app
            mvn package
      
      - run:
          name: docker build
          command: docker build -t mvnsample:build .
      
      - run:
          name: store docker image
          command: |
            mkdir -p workspace
            docker save mvnsample:build -o workspace/image.tar

      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar

workflows:
  version: 2.1
  scan-image:
    jobs:
      - docker-build
      - scan/scan_image:
          requires:
            - docker-build
          context: jb_prisma
          prisma_cloud_compute_url: https://asia-northeast1.cloud.twistlock.com
          prisma_cloud_compute_user: a_niida@jbat.co.jp
          prisma_cloud_compute_pass: PC_COMPUTE_PASS
          image: mvnsample:build
          image_tar: image.tar
          vulnerability_threshold: critical
          compliance_threshold: ''
          only_fixed: true
          filters:
            branches:
              only: /security\/twistlock.*/
