version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run: 
          name: mvn package
          command: |
            cd web-app
            mvn package

      - store_artifacts:
          path: ./web-app/target/web-app.war
          destination: warfile

workflows:
  version: 2.1
  mvn_build:
    jobs:
      - build
