version: 2.1

jobs:
  docker-build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      
      - setup_remote_docker

      - run: 
          name: mvn package
          command: |
            cd web-app
            mvn package
      
      - run:
          name: docker build
          command: docker build -t nidstyle3/mvnsample:${CIRCLE_SHA1} .
      
      - run:
          name: store docker image
          command: |
            mkdir -p workspace
            docker save mvnsample:build -o workspace/image.tar

      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
            
  scan-image:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: scan image MEDIUM,HIGH
          command: trivy --light --exit-code 0 --no-progress --severity MEDIUM,HIGH --input /tmp/workspace/image.tar

      - run:
          name: scan image CRITICAL
          command: trivy --light --exit-code 1 --no-progress --severity CRITICAL --input /tmp/workspace/image.tar

  check-compliance:
    docker:
      - image: goodwithtech/dockle:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: scan image file
          command: dockle --exit-code 1 --exit-level warn --input /tmp/workspace/image.tar

workflows:
  version: 2.1
  scan-image:
    jobs:
      - docker-build
      - scan-image:
          requires:
            - docker-build
          filters:
            branches:
              only: /security\/trivy*/
      - check-compliance:
          requires:
            - docker-build
          filters:
            branches:
              only: /security\/trivy*/
