version: 2.1

orbs:
  twistcli: twistlock/twistcli-scan@1.0.5

jobs:
  docker-build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      
      - setup_remote_docker

      - run: 
          name: mvn package
          command: |
            cd web-app
            mvn package
      
      - run:
          name: docker build
          command: docker build -t nidstyle3/mvnsample:${CIRCLE_SHA1} .
      
      - run:
          name: store docker image
          command: |
            mkdir -p workspace
            docker save nidstyle3/mvnsample:$CIRCLE:SHA1 -o workspace/image.tar

      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar

workflows:
  version: 2.1
  scan-image:
    jobs:
      - docker-build
      - twistcli/scan-image:
          requires:
            - docker-build
          context: jb_prisma
          image: "nidstyle3/mvnsample:${CIRCLE_SHA1}"
          image-tar: image.tar
          vuln-thresh: high
          comp-thresh: critical
          only-fixed: true
          filters:
            branches:
              only: /security\/twistlock.*/
